# -*- coding: utf-8 -*-
r"""Dropdown choices for every fill-in-the-blank blank.

Viktor: "fill in the blanks should have a dropdown at each location with lets
say 5-10 different choices, some of the choices should be not so obvious near
miss."

So the distractors here are not filler. Each one is a thing a person could
plausibly write: the two terms that are always confused (equivariant /
invariant, drift / diffusion, linear / quadratic), the formula with one index
off (J_l instead of J_{l-1}), the operation that is also symmetric but is not
the one PointNet uses (sum pooling for max pooling), the family that sounds
like it belongs but does not (distillation-based among the continual-learning
four).

DISTRACTORS[question id] is a list, one entry per blank, of wrong answers.
The correct answer is added by the build and the list is then shuffled with a
seed derived from the blank, so the right one is not always in the same place.
"""

DISTRACTORS = {
    # ---------------------------------------------------------------- exam 01
    "e01q31": [
        ["$K(D-1)+1$", "$D(K+1)-1$", "$DK$", "$K + D - 1$", "$(K-1)/D + 1$"],
        [r"$R_{l-1} + (K_{\text{eff},l}-1)\,J_{l}$",
         r"$R_{l-1} + K_{\text{eff},l}\,J_{l-1}$",
         r"$R_{l-1} + (K_{\text{eff},l}-1)\,S_{l}$",
         r"$R_{l-1}\,J_{l-1} + K_{\text{eff},l}$",
         r"$R_{l-1} + (K_{\text{eff},l}+1)\,J_{l-1}$"],
        [r"$J_{l-1} + S_l$", r"$J_{l}\,S_{l-1}$", r"$J_{l-1}/S_l$",
         r"$J_{l-1}\,K_l$", r"$S_l$"],
    ],
    "e01q32": [["$O(n d^2)$", "$O(n)$", "$O(1)$", "$O(n^2)$", "$O(\\log n)$", "$O(nd)$"]] * 6,
    "e01q33": [
        ["$M/2 \\times M/2$", "$2M \\times 2M$", "$7 \\times 7$", "$M \\times 1$"],
        ["$M$", "$\\lceil M/2 \\rceil$", "$M/4$", "$2M$", "$1$"],
        ["within-window", "cross-channel", "global", "hierarchical", "shifted"],
    ],
    "e01q34": [
        ["$2L$", "$1 + L$", "$3L$", "$2L - 1$", "$L^3$"],
        ["$(1+2L)^2$", "$1 + 2L^3$", "$3(1+2L)$", "$(2L)^3$", "$8L^3$"],
        ["a cube of side $1+L$", "$(1+2L)^3$ voxels", "a cube of side $3$",
         "nothing at all"],
    ],
    "e01q35": [
        ["$A - D$", "$D + A$", "$A$", "$D^{-1}A$", "$I - A$"],
        ["$D^{-1/2} A D^{-1/2}$", "$I + D^{-1/2} A D^{-1/2}$", "$D^{-1} L$",
         "$L D^{-1}$", "$I - D^{-1} A$"],
        [r"$\sigma(D^{-1/2} A D^{-1/2} H^{(l)} W^{(l)})$",
         r"$\sigma(\tilde A H^{(l)} W^{(l)})$",
         r"$\sigma(\tilde D^{-1}\tilde A H^{(l)} W^{(l)})$",
         r"$\tilde D^{-1/2}\tilde A \tilde D^{-1/2} H^{(l)} W^{(l)}$"],
    ],
    "e01q36": [
        ["quasi-metric", "semi-metric", "ultrametric", "premetric", "a norm"],
        ["over-smoothing", "mode collapse", "overfitting", "vanishing gradients",
         "dead units"],
        ["$0$", "$2m$", "$m^2$", "$1$"],
    ],
    # ---------------------------------------------------------------- exam 02
    "e02q27": [
        ["keys", "values", "keys and values", "queries and keys"],
        ["queries", "values only", "queries and values", "keys only"],
        ["one per modality", "two joint", "a scalar score", "no"],
        ["one joint", "a single fused vector", "one per layer",
         "a similarity matrix"],
    ],
    "e02q28": [
        ["a simple average", "an exact copy", "a gradient update",
         "a momentum of the gradients", "a running variance"],
        ["weight decay", "gradient reversal", "batch normalisation",
         "gradient clipping", "dropout"],
        ["uniform", "sharpened", "zero-mean", "bimodal"],
        ["fixed, non-uniform", "one-hot", "Gaussian", "sharpened"],
    ],
    "e02q29": [
        ["$\\log(N-1)$", "$N$", "$\\log_2 N$", "$-\\log N$", "$\\log N / N$"],
        ["floor", "lower bound", "asymptote", "threshold"],
    ],
    "e02q30": [
        ["$AB$", "$A + B$", "$B^{\\top}A$", "$AB^{\\top}$"],
        ["$dr$", "$d^2 r$", "$2d + r$", "$r^2$"],
        ["zero map", "scaling by $\\lambda$", "transpose", "projection"],
        ["$+\\lambda$", "$-1$", "$\\lambda^{-1}$", "$0$"],
    ],
    "e02q31": [
        ["bias–variance", "exploration–exploitation",
         "precision–recall", "plasticity–elasticity"],
    ] + [["regularisation-based", "replay-based", "optimisation-based",
          "architecture-based", "distillation-based", "ensemble-based",
          "curriculum-based"]] * 4,
    "e02q32": [
        ["diffusion term", "score function", "noise schedule", "Wiener process"],
        ["drift", "score function", "noise level", "step size"],
        ["Poisson process", "Markov chain", "Gaussian mixture",
         "Ornstein–Uhlenbeck process"],
        ["variance-exploding", "variance-reducing", "mean-preserving",
         "signal-preserving", "norm-preserving"],
        ["variance-preserving", "variance-reducing", "mean-exploding",
         "signal-exploding", "norm-exploding"],
    ],
    "e02q33": [
        ["position $(x,y,z)$ alone", "view direction $(\\theta,\\phi)$ alone",
         "a ray and a depth", "pixel coordinates"],
        ["colour $\\mathbf{c}$ alone", "density $\\sigma$ alone",
         "transmittance $T$ and colour $\\mathbf{c}$", "an RGBA value"],
        ["the position", "the transmittance", "the number of samples",
         "the camera intrinsics"],
        ["colour is the same from every direction",
         "the network would otherwise be too large",
         "density is easier to learn than colour",
         "the renderer requires it"],
    ],
    # ---------------------------------------------------------------- exam 03
    "e03q31": [
        ["$(H + 2P - K)/S$", "$\\lfloor (H - K + 2P)/S \\rfloor$",
         "$\\lceil (H + 2P - K)/S \\rceil + 1$",
         "$\\lfloor (H + P - K)/S \\rfloor + 1$", "$H/S$"],
        ["$K\\,C_{\\text{in}} C_{\\text{out}}$", "$K^2 C_{\\text{in}}$",
         "$K^2 (C_{\\text{in}} + C_{\\text{out}})$", "$K^2 C_{\\text{out}}$",
         "$2K C_{\\text{in}} C_{\\text{out}}$"],
        ["$C_{\\text{in}}$", "$K^2$", "$C_{\\text{in}} C_{\\text{out}}$", "$1$"],
    ],
    "e03q32": [
        ["invariant", "covariant", "permutation-free", "order-sensitive"],
        ["layer normalisation", "a causal mask", "a residual connection",
         "token embeddings"],
        ["before", "instead of", "in place of",
         "twice, before and after", "only in the decoder"],
    ],
    "e03q33": [
        ["linear", "logarithmic", "constant", "cubic"],
        ["quadratic", "logarithmic", "constant", "cubic"],
        ["the windows stay the same size", "the cost stays linear",
         "the model has fewer parameters",
         "attention becomes global in a single layer"],
    ],
    "e03q34": [
        ["colour channel order", "the number of points", "feature scaling",
         "spatial (rigid) transformation"],
        ["point permutation", "the number of points", "feature scaling",
         "sampling density"],
        ["point permutation", "colour channel order", "feature scaling",
         "spatial (rigid) transformation"],
        ["asymmetric", "monotone", "linear", "injective"],
        ["sum pooling", "average pooling", "the T-Net",
         "a fully connected layer"],
    ],
    "e03q35": [
        ["sigmoid", "layer normalisation", "$L_2$ normalisation", "a hard max"],
        ["all nodes", "the whole graph", "the node's own features",
         "the edges of the graph"],
        ["skip connections", "dropout", "batch normalisation",
         "gradient clipping", "attention heads"],
        ["self-loops", "dropout", "batch normalisation", "gradient clipping",
         "attention heads"],
    ],
    "e03q36": [
        [r"$\max(0,\ \mathcal{D}(a,n) - \mathcal{D}(a,p) + m)$",
         r"$\max(0,\ \mathcal{D}(a,p) - \mathcal{D}(a,n) - m)$",
         r"$\mathcal{D}(a,p) - \mathcal{D}(a,n) + m$",
         r"$\max(0,\ \mathcal{D}(a,p) + \mathcal{D}(a,n) - m)$"],
        ["easy", "semi-hard", "anchor", "marginal", "trivial"],
        ["hard", "easy", "marginal", "trivial", "anchor"],
    ],

    # ---------------------------------------------------------------- exam 04
    "e04q31": [
        ["$O(n d^2)$", "$O(n^2)$", "$O(n d)$", "$O(n^2 d^2)$", "$O(d^2)$"],
        ["$O(n)$", "$O(\\log n)$", "$O(n^2)$", "$O(d)$", "$O(n/r)$"],
        ["$O(n^2 d)$", "$O(n d)$", "$O(d^2)$", "$O(n^2 d^2)$", "$O(n)$"],
        ["$O(1)$", "$O(\\log_k n)$", "$O(n^2)$", "$O(n d)$", "$O(d)$"],
        ["$n > d$", "$n < d^2$", "$n = d$", "$d < n^2$", "$n \\ll 1$"],
    ],
    "e04q32": [
        ["square", "logarithm", "fourth power", "square root"],
        ["$4$", "$2$", "$16$", "$64$", "$3$"],
        ["in the interior of objects", "uniformly through the volume",
         "at the grid boundary", "near the sensor", "in the occupied voxels only"],
        ["unknown", "free", "boundary", "surface", "split"],
        ["unknown", "dense", "boundary", "leaf", "split"],
        ["unknown", "boundary", "split", "partial", "dense"],
        ["occupied", "empty", "boundary", "unknown", "leaf"],
    ],
    "e04q33": [
        [r"$(\mathbf{x}_1-\mathbf{x}_2)^{\top}(\mathbf{x}_1-\mathbf{x}_2)$",
         r"$\mathbf{x}_1^{\top}M\mathbf{x}_2$",
         r"$M(\mathbf{x}_1-\mathbf{x}_2)^{\top}(\mathbf{x}_1-\mathbf{x}_2)$",
         r"$(\mathbf{x}_1-\mathbf{x}_2)M^{\top}(\mathbf{x}_1-\mathbf{x}_2)$",
         r"$\lVert M(\mathbf{x}_1-\mathbf{x}_2)\rVert$"],
        ["orthogonal", "symmetric and invertible", "diagonal and positive",
         "any real matrix", "skew-symmetric"],
        ["it has too many parameters", "the distance is not differentiable",
         "the gradient is undefined at zero", "it is not symmetric"],
        ["$WW^{\\top}$", "$W^2$", "$W + W^{\\top}$", "$W^{-1}W$"],
        [r"$\lVert \mathbf{x}_1-\mathbf{x}_2\rVert^2$",
         r"$W\lVert \mathbf{x}_1-\mathbf{x}_2\rVert^2$",
         r"$\lVert W\mathbf{x}_1\rVert^2 - \lVert W\mathbf{x}_2\rVert^2$",
         r"$\lVert W(\mathbf{x}_1\mathbf{x}_2)\rVert^2$"],
        ["triplet", "contrastive", "bilinear", "cross-modal", "coordination"],
    ],
    "e04q34": [
        ["exact copy", "frozen snapshot", "randomly reinitialised copy",
         "gradient-free clone", "larger pre-trained model"],
        ["gradient reversal", "detached loss", "weight decay", "learning-rate warmup"],
        ["sharpening", "whitening", "normalisation", "clipping"],
        ["centering", "smoothing", "label smoothing", "temperature warmup"],
        ["$<$", "$=$", "$\\ge$", "$\\approx$"],
    ],
    "e04q35": [
        [r"$\sqrt{\beta_k}\,\mathbf{x}_{k-1}$", r"$(1-\beta_k)\mathbf{x}_{k-1}$",
         r"$\mathbf{x}_{k-1}$", r"$\sqrt{1-\bar\alpha_k}\,\mathbf{x}_{k-1}$"],
        ["$(1-\\beta_k)I$", "$\\sqrt{\\beta_k}\\,I$", "$\\beta_k^2 I$", "$I$"],
        ["$\\beta_k$", "$1+\\beta_k$", "$\\sqrt{1-\\beta_k}$",
         "$\\prod_{s\\le k}\\beta_s$"],
        [r"$\sum_{s\le k}\alpha_s$", r"$\alpha_k^{k}$",
         r"$\prod_{s\le k}\beta_s$", r"$1-\prod_{s\le k}\alpha_s$"],
        [r"$\bar\alpha_k\mathbf{x}_0 + (1-\bar\alpha_k)\varepsilon$",
         r"$\sqrt{\alpha_k}\,\mathbf{x}_0 + \sqrt{1-\alpha_k}\,\varepsilon$",
         r"$\sqrt{\bar\alpha_k}\,\mathbf{x}_0 + (1-\bar\alpha_k)\varepsilon$",
         r"$\mathbf{x}_0 + \sqrt{\bar\alpha_k}\,\varepsilon$"],
        [r"$\lVert \mathbf{x}_0 - \mathbf{x}_\theta\rVert^2$",
         r"$\lVert \mathbf{x}_k - \mathbf{x}_{k-1}\rVert^2$",
         r"$-\log p_\theta(\mathbf{x}_0)$",
         r"$\lVert s_\theta - \nabla_{\mathbf{x}}\log p\rVert^2$"],
    ],
    "e04q36": [
        [r"$\sigma(\mathbf{r}(t))$", "$\\alpha_t$", "$1-T(t)$", r"$\mathbf{c}(t)$"],
        ["$T(t)$", "$\\alpha_t$", "$\\delta_t$", r"$\mathbf{c}(\mathbf{r}(t))$"],
        [r"$\mathbf{c}(\mathbf{r}(t))$", r"$\sigma(\mathbf{r}(t),\mathbf{d})$",
         r"$\mathbf{c}(\mathbf{d})$", r"$T(t)\,\mathbf{c}$"],
        [r"$\exp\bigl(\int_{t_n}^{t}\sigma(\mathbf{r}(s))\,\mathrm{d}s\bigr)$",
         r"$1-\exp\bigl(-\int_{t_n}^{t}\sigma(\mathbf{r}(s))\,\mathrm{d}s\bigr)$",
         r"$\prod_{j<i}\alpha_j$", r"$\exp(-\sigma(\mathbf{r}(t)))$"],
        ["opacity", "radiance", "absorption", "albedo", "density"],
        ["ray marching", "z-buffering", "rasterisation", "max compositing"],
        [r"$\exp(-\sigma_i\delta_i)$", r"$\sigma_i\delta_i$",
         r"$1-\sigma_i$", r"$T_i\sigma_i$"],
    ],

    # ---------------------------------------------------------------- exam 05
    "e05q31": [
        ["$Wh^{(t-1)} + Ux^{(t)}$", "$b + Wx^{(t)} + Uh^{(t-1)}$",
         "$b + Wh^{(t)} + Ux^{(t-1)}$", r"$\tanh(Wh^{(t-1)} + Ux^{(t)})$"],
        [r"$\mathrm{ReLU}(a^{(t)})$", r"$\mathrm{softmax}(a^{(t)})$",
         r"$\sigma(a^{(t)})$", "$a^{(t)}$"],
        [r"$\partial h^{(t)}/\partial W$", r"$\partial \mathcal{L}/\partial h^{(k)}$",
         r"$\partial h^{(k-1)}/\partial h^{(k)}$", r"$\partial a^{(k)}/\partial h^{(k)}$"],
        [r"$t\gamma$", r"$\gamma/t$", r"$\gamma$", r"$\log \gamma^{t}$"],
        ["exploding gradients", "dead neurons", "over-smoothing",
         "catastrophic forgetting"],
        ["vanishing gradients", "mode collapse", "overfitting", "saturation"],
        # the two best distractors here are the remedies for the *other* two
        # failures, which is exactly the confusion the question is testing
        ["truncated BPTT", "LSTM or GRU gating", "weight decay",
         "layer normalisation", "a smaller learning rate"],
    ],
    "e05q32": [
        [r"$3\times3$", r"$4\times4$", r"$M\times M$", r"$2\times1$"],
        ["$2$", "$8$", "$16$", "$M^2$"],
        ["$4$", "$1$", "$8$", "$M$"],
        [r"$(H/2,\ W/2,\ 4C)$", r"$(H/4,\ W/4,\ 2C)$",
         r"$(H/2,\ W/2,\ C/2)$", r"$(2H,\ 2W,\ C/2)$"],
        ["$M$", r"$\lceil M/2 \rceil$", "$M/4$", "$1$", "$2M$"],
    ],
    "e05q33": [
        ["$A$", "$A - I$", "$D - A$", r"$A + A^{\top}$"],
        ["$A$", "$L$", "$I$", r"$A^{\top}$"],
        [r"$\sigma\bigl(\tilde A H^{(l)}W^{(l)}\bigr)$",
         r"$\sigma\bigl(\tilde D^{-1}\tilde A H^{(l)}W^{(l)}\bigr)$",
         r"$\sigma\bigl(\tilde D^{-1/2}A\tilde D^{-1/2}H^{(l)}W^{(l)}\bigr)$",
         r"$\tilde D^{-1/2}\tilde A\tilde D^{-1/2}H^{(l)}W^{(l)}$"],
        ["$1$-hop", "$2L$-hop", "$L^2$-hop", r"$\log L$-hop"],
        ["8--16 layers", "50 layers", "1 layer", "10--20 layers"],
        ["over-squashing", "under-reaching", "over-fitting", "vanishing gradients"],
    ],
    "e05q34": [
        [r"$\mathbf{x}_A \odot \mathbf{x}_B$", r"$\mathbf{x}_A^{\top}\mathbf{x}_B$",
         r"$W(\mathbf{x}_A\otimes\mathbf{x}_B)$",
         r"$\max(\mathbf{x}_A,\mathbf{x}_B)$"],
        [r"$\mathbf{w}(\mathbf{x}_A + \mathbf{x}_B)$",
         r"$\mathbf{w}(\mathbf{x}_A^{\top}\mathbf{x}_B)$",
         r"$\mathbf{x}_A \odot \mathbf{w}$",
         r"$W(\mathbf{x}_A\otimes\mathbf{x}_B)$"],
        ["every feature", "the mean of the other vector", "the first feature",
         "no feature of the other modality"],
        # the tensor-fusion form is the near miss: the appended 1s are the
        # only difference, and they are the whole difference
        [r"$W([\mathbf{x}_A,1]^{\top}\!\cdot[\mathbf{x}_B,1])$",
         r"$W(\mathbf{x}_A \odot \mathbf{x}_B)$",
         r"$\mathbf{x}_A^{\top}W\mathbf{x}_B$",
         r"$W\mathbf{x}_A + W\mathbf{x}_B$"],
        ["feature $i$ meets feature $i$", "each modality votes independently",
         "the unimodal terms are recovered as well",
         "one modality gates the other channel by channel"],
        ["bilinear", "tensor", "element-wise", "late"],
    ],
    "e05q35": [
        ["$W + AB$", "$WBA$", "$BA$", "$W + B + A$"],
        [r"$\mathbb{R}^{r\times d}$", r"$\mathbb{R}^{d\times d}$",
         r"$\mathbb{R}^{r\times r}$", r"$\mathbb{R}^{d}$"],
        [r"$\mathbb{R}^{d\times r}$", r"$\mathbb{R}^{d\times d}$",
         r"$\mathbb{R}^{r\times r}$", r"$\mathbb{R}^{r}$"],
        [r"$W\mathbf{x} + BA\mathbf{x}$",
         r"$\tfrac{\alpha}{r}(W + BA)\mathbf{x}$",
         r"$W\mathbf{x} + \tfrac{r}{\alpha}BA\mathbf{x}$", r"$BA\mathbf{x}$"],
        ["zero", "the identity", "orthogonal", "the pre-trained weights"],
        ["random", "the identity", "orthogonal", "small and positive"],
        ["small but non-zero", "random", "the identity", "approximately zero"],
        ["$2r/d$", "$d/r$", "$d^2/2r$", "$r/2d$"],
    ],
    "e05q36": [
        [r"$s(\mathbf{x}\mid\mathbf{c})$",
         r"$\nabla_{\mathbf{x}}\log p(\mathbf{c})$",
         r"$\varepsilon_\theta(\mathbf{x},t)$", r"$\log p(\mathbf{x})$"],
        [r"$\nabla_{\mathbf{x}}\log p(\mathbf{x}\mid\mathbf{c})$",
         r"$\nabla_{\theta}\log p(\mathbf{c}\mid\mathbf{x})$",
         r"$\log p(\mathbf{c}\mid\mathbf{x})$",
         r"$\nabla_{\mathbf{x}}\log p(\mathbf{c})$"],
        [r"$\gamma\,s(\mathbf{x}) + (1-\gamma)\,s(\mathbf{x}\mid\mathbf{c})$",
         r"$s(\mathbf{x}) + \gamma\,s(\mathbf{x}\mid\mathbf{c})$",
         r"$(1-\gamma)\,s(\mathbf{x}\mid\mathbf{c}) + \gamma\,s(\mathbf{x})$",
         r"$\gamma\,s(\mathbf{x}\mid\mathbf{c})$"],
        ["interpolation", "a convex combination", "a rescaling", "a projection"],
        ["one", "three", "$K$", "no extra"],
    ],
}
