# -*- coding: utf-8 -*-
r"""Merge the extracted questions with the hand-written dropdown choices and
emit data/questions.js.

A .js file rather than .json because the site has to work when opened straight
from disk: a file:// page is not allowed to fetch() a sibling file, but it can
load a script that assigns to window.QUESTIONS.
"""
import hashlib
import io
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from blank_options import DISTRACTORS
from numeric_expected import EXPECTED

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "data")


def shuffled(items, seed):
    """Deterministic shuffle, so a blank's choices sit in a stable order."""
    rnd = random.Random(int(hashlib.md5(seed.encode()).hexdigest()[:8], 16))
    out = list(items)
    rnd.shuffle(out)
    return out


def main():
    src = json.load(io.open(os.path.join(DATA, "generated.json"),
                            encoding="utf-8"))
    problems = []
    for q in src:
        q.pop("raw_answers", None)
        if q["type"] == "numeric":
            # One labelled box per quantity: the site marks each separately and
            # says which one is wrong, so a pair must be (label, value) and the
            # label must actually name something.
            want = EXPECTED.get(q["id"])
            if want is None:
                problems.append("%s: no expected numbers written" % q["id"])
                continue
            bad = [p for p in want
                   if not (isinstance(p, tuple) and len(p) == 2
                           and isinstance(p[0], str) and p[0].strip()
                           and isinstance(p[1], (int, float)))]
            if bad:
                problems.append("%s: %d entries are not (label, number): %r"
                                % (q["id"], len(bad), bad[:2]))
                continue
            q["expected"] = [v for _, v in want]
            q["expectLabels"] = [lab for lab, _ in want]
            continue
        if q["type"] != "blanks":
            continue
        pools = DISTRACTORS.get(q["id"])
        if pools is None:
            problems.append("%s: no dropdown choices written" % q["id"])
            continue
        if len(pools) != len(q["answers"]):
            problems.append("%s: %d blanks but %d choice lists"
                            % (q["id"], len(q["answers"]), len(pools)))
            continue
        choices, correct = [], []
        for k, (ans, wrong) in enumerate(zip(q["answers"], pools)):
            opts = [ans] + [w for w in wrong if w != ans]
            if len(opts) < 5:
                problems.append("%s blank %d: only %d choices"
                                % (q["id"], k + 1, len(opts)))
            opts = shuffled(opts, "%s-%d" % (q["id"], k))
            choices.append(opts)
            correct.append(opts.index(ans))
        q["choices"] = choices
        q["correct"] = correct

    if problems:
        for p in problems:
            print("!! " + p)
        raise SystemExit(1)

    js = ("// GENERATED by tools/build_data.py -- do not edit by hand.\n"
          "// Source: the exam papers in ../Exams/src.\n"
          "window.QUESTIONS = %s;\n"
          % json.dumps(src, ensure_ascii=False, indent=1))
    io.open(os.path.join(DATA, "questions.js"), "w", encoding="utf-8",
            newline="\n").write(js)

    from collections import Counter
    print("wrote data/questions.js -- %d questions" % len(src))
    for k, v in sorted(Counter(q["type"] for q in src).items()):
        print("   %-8s %d" % (k, v))
    comp = Counter(q["type"] + (":" + q["sub"] if q.get("sub") else "") for q in src)
    print("   composition a 50-question paper will aim for:")
    for k in sorted(comp):
        print("      %-16s %3d in db  ->  %4.1f in 50" % (k, comp[k], 50.0 * comp[k] / len(src)))
    weeks = Counter(q["week"] for q in src)
    print("   weeks: " + ", ".join("%s %d" % (k, weeks[k])
                                   for k in sorted(weeks, key=lambda w: (len(w), w))))
    nblank = sum(len(q["choices"]) for q in src if q["type"] == "blanks")
    nopt = sum(len(c) for q in src if q["type"] == "blanks" for c in q["choices"])
    print("   %d blanks, %.1f choices each on average" % (nblank, nopt / nblank))
    nums = [q for q in src if q["type"] == "numeric"]
    nfield = sum(len(q["expected"]) for q in nums)
    print("   %d numeric boxes over %d questions, %.1f each"
          % (nfield, len(nums), nfield / len(nums)))


if __name__ == "__main__":
    main()
